# Key bindings map keyboard keys to actions
key_bindings = [
    [
        "W",
        "move_up",
    ],
    [
        "A",
        "move_left",
    ],
    [
        "S",
        "move_down",
    ],
    [
        "D",
        "move_right",
    ],
    [
        "SPACE",
        "left_click",
    ],
    [
        "E",
        "right_click",
    ],
]
polling_rate = 50

# Grid size for grid-based navigation
[grid_size]
width = 3
height = 3

# Smooth jump speed for mouse movements
smooth_jump_speed = 5.0
