# Key bindings map keyboard keys to actions
key_bindings = [
    [
        "W",
        "move_up",
    ],
    [
        "A",
        "move_left",
    ],
    [
        "S",
        "move_down",
    ],
    [
        "D",
        "move_right",
    ],
    [
        "SPACE",
        "left_click",
    ],
    [
        "E",
        "right_click",
    ],
    [
        "Escape",
        "exit",
    ],
    [
        "LeftShift",
        "slow_mouse",
    ],
    [
        "RightShift",
        "slow_mouse",
    ],
]
polling_rate = 1

# Grid size
grid_size = { width = 10, height = 10 }

# Mouse movement parameters
starting_speed = 2     # Initial speed in pixels
acceleration = 5       # Pixels per acceleration step
acceleration_rate = 50 # Polling cycles before applying acceleration
